// prisma/seeds/documents.ts — Official Forms & Documents per country

export const DOCUMENTS = [
  // INDIA
  { countryCode:'IND', code:'FORM_6',  name:'Form 6 — New Voter Registration', purpose:'Registration for first-time voters and those enrolling in a new constituency', targetPersonas:['P01','P02'], portalUrl:'https://voters.eci.gov.in', processingMin:15, processingMax:30, requiredDocs:['Proof of Age (Aadhaar/Passport/PAN/Marksheet)','Proof of Address (Aadhaar/Utility Bill/Bank Passbook)','Passport-size photograph'], volatilityClass:'STABLE' },
  { countryCode:'IND', code:'FORM_6A', name:'Form 6A — NRI/Overseas Voter Registration', purpose:'Registration for Non-Resident Indians as overseas electors', targetPersonas:['P03'], portalUrl:'https://voters.eci.gov.in', processingMin:30, processingMax:60, requiredDocs:['Indian Passport (valid)','Proof of overseas residence'], volatilityClass:'STABLE' },
  { countryCode:'IND', code:'FORM_8',  name:'Form 8 — Correction / EPIC Replacement', purpose:'Correct voter roll details, replace lost EPIC, mark PwD status, shift residence within same constituency', targetPersonas:['P01','P02','P04','P05'], portalUrl:'https://voters.eci.gov.in', processingMin:7, processingMax:21, requiredDocs:['Existing EPIC number or Aadhaar','Supporting document for correction'], volatilityClass:'STABLE' },
  { countryCode:'IND', code:'FORM_8A', name:'Form 8A — Constituency Transfer', purpose:'Transfer voter registration when moving to a new constituency', targetPersonas:['P02'], portalUrl:'https://voters.eci.gov.in', processingMin:15, processingMax:30, requiredDocs:['Proof of new address','Existing EPIC'], volatilityClass:'STABLE' },
  // USA
  { countryCode:'USA', code:'NVRA_FORM', name:'National Voter Registration Form', purpose:'Federal voter registration form accepted by most states', targetPersonas:['P01'], portalUrl:'https://vote.gov', downloadUrl:'https://www.eac.gov/voters/national-mail-voter-registration-form', processingMin:7, processingMax:30, requiredDocs:['State ID or last 4 SSN digits','Proof of citizenship (varies by state)'], volatilityClass:'MEDIUM' },
  { countryCode:'USA', code:'FPCA', name:'Federal Post Card Application (FPCA)', purpose:'Register and request absentee ballot for military and overseas citizens under UOCAVA', targetPersonas:['P03'], portalUrl:'https://www.fvap.gov', processingMin:3, processingMax:14, requiredDocs:['Valid ID number','Overseas address'], volatilityClass:'STABLE' },
  { countryCode:'USA', code:'FWAB', name:'Federal Write-in Absentee Ballot (FWAB)', purpose:'Emergency backup ballot for overseas voters who did not receive their regular absentee ballot in time', targetPersonas:['P03','P06'], portalUrl:'https://www.fvap.gov', processingMin:0, processingMax:0, requiredDocs:['FPCA confirmation'], volatilityClass:'STABLE' },
  // UK
  { countryCode:'GBR', code:'VAC_FORM', name:'Voter Authority Certificate Application', purpose:'Free photo ID for voters who lack accepted photo ID documents', targetPersonas:['P01','P04','P05','P06'], portalUrl:'https://www.gov.uk/apply-for-photo-id-voter-authority-certificate', processingMin:5, processingMax:10, requiredDocs:['Passport-style photograph','National Insurance number'], volatilityClass:'MEDIUM' },
  { countryCode:'GBR', code:'POSTAL_VOTE', name:'Postal Vote Application', purpose:'Apply to vote by post — available to all voters, no reason required', targetPersonas:['P02','P03','P04','P05'], portalUrl:'https://www.gov.uk/apply-postal-vote', processingMin:5, processingMax:11, requiredDocs:['Date of birth','National Insurance number'], volatilityClass:'MEDIUM' },
  { countryCode:'GBR', code:'PROXY_VOTE', name:'Proxy Vote Application', purpose:'Appoint someone you trust to vote on your behalf', targetPersonas:['P03','P04','P05'], portalUrl:'https://www.gov.uk/apply-proxy-vote', processingMin:5, processingMax:11, requiredDocs:['Proxy\'s full name and address','Reason for proxy'], volatilityClass:'MEDIUM' },
  // CANADA
  { countryCode:'CAN', code:'SPECIAL_BALLOT', name:'Special Ballot Application', purpose:'Apply to vote by mail — available to any eligible voter', targetPersonas:['P02','P03','P04','P05'], portalUrl:'https://www.elections.ca/content.aspx?section=vot&dir=bkg&document=index&lang=e', processingMin:3, processingMax:14, requiredDocs:['Canadian citizenship proof','Proof of address'], volatilityClass:'MEDIUM' },
  // AUSTRALIA
  { countryCode:'AUS', code:'ENROLMENT_FORM', name:'AEC Enrolment Form', purpose:'Enrol to vote or update enrolment details (name, address)', targetPersonas:['P01','P02'], portalUrl:'https://www.aec.gov.au/enrol', processingMin:1, processingMax:7, requiredDocs:['Australian citizenship','Proof of identity'], volatilityClass:'STABLE' },
  { countryCode:'AUS', code:'POSTAL_VOTE_AUS', name:'AEC Postal Vote Application', purpose:'Apply to vote by post for any reason', targetPersonas:['P02','P03','P04','P05'], portalUrl:'https://www.aec.gov.au/election/pva.htm', processingMin:3, processingMax:10, requiredDocs:['Enrolment details'], volatilityClass:'MEDIUM' },
];
